development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pmo
  pool: 5
  username: root
  password: mysql
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pmo
  pool: 5
  username: root
  password: mysql
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pmo
  pool: 5
  username: root
  password: mysql
  host: localhost